import { useState } from 'react';
import Head from 'next/head';
import { Radio } from 'antd';
import Image from 'next/image';

export default function Home() {
    const [type, setType] = useState('ice');

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="m-auto w-[700px] p-[30px] ">
                <Radio.Group
                    className="flex justify-center mb-[20px]"
                    defaultValue="ice"
                    buttonStyle="solid"
                    onChange={(e) => setType(e.target.value)}
                    value={type}
                >
                    <Radio.Button className="w-[150px] text-center" value="ice">
                        얼음 깨기
                    </Radio.Button>
                    <Radio.Button className="w-[150px] text-center" value="roulette">
                        룰렛
                    </Radio.Button>
                </Radio.Group>

                {type === 'ice' && <IceGame />}
                {type === 'roulette' && <RouletteGame />}
            </main>
        </>
    );
}

import background from 'public/images/ice_bg.png';

function IceGame() {
    return (
        <article>
            <Image src={background} alt="background" />
        </article>
    );
}
function RouletteGame() {
    return <article></article>;
}
